### ISSUE TITLE
error ? !

### ISSUE THREAD

**Issue by bilalbaz1** [nhancv/nc-flutter-webrtc-ex#2]
I get a `GET http://127.0.0.1:3000/ 404 (Not Found)` error. What is the reason? (in the console)

https://i.hizliresim.com/nZrNsB.png

**Comment by nhancv** [comment]
http://127.0.0.1:3000 is for socket server only. (webrtc-nestjs-server)
http://127.0.0.1:4000 for web rtc client (webrtc-web-client)
